# Generated by Django 2.0.7 on 2018-07-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_info', '0002_requestdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='last_request',
            field=models.DateTimeField(),
        ),
    ]
