# Generated by Django 2.0.7 on 2018-07-29 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dog_info', '0003_auto_20180729_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='earliest_request',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
