# Generated by Django 2.0.7 on 2018-08-02 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dog_info', '0007_auto_20180802_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
